# Generated by Django 5.2.9 on 2026-01-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content_A', models.TextField(blank=True)),
                ('content_B', models.TextField(blank=True)),
                ('content_C', models.TextField(blank=True)),
            ],
        ),
    ]
