# Generated by Django 5.2.9 on 2026-01-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelink',
            name='menu_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
